<a href="https://colab.research.google.com/github/leadeeerq/data-science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x = np.array([1, 3])
x

array([1, 3])

In [4]:
print(x)

[1 3]


In [5]:
type(x)

numpy.ndarray

In [6]:
x.ndim

1

In [7]:
x.shape

(2,)

In [8]:
x.size

2

In [9]:
x.dtype

dtype('int64')

In [11]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


### 2D Array

In [17]:
x = np.array([[1,2],[-3,1]])
print(x)
x.ndim
x.shape

[[ 1  2]
 [-3  1]]


(2, 2)

In [18]:
x = np.array([[1, 3, 5], [-1, 2, 4]])

In [19]:
x.shape

(2, 3)

### 3D Array

In [25]:
x = np.array(
    [[[4,3,1],
      [3,2,1]],
     [[1,4,5],
      [-4,1,4]],
     [[3,2,1],
      [1,2,3]]], dtype='float'
)
print(x)

[[[ 4.  3.  1.]
  [ 3.  2.  1.]]

 [[ 1.  4.  5.]
  [-4.  1.  4.]]

 [[ 3.  2.  1.]
  [ 1.  2.  3.]]]


In [23]:
x.shape

(3, 2, 3)

In [24]:
x.ndim

3

In [27]:
np.eye(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
np.ones(shape=(3,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.full(shape=(3,4), fill_value = 4, dtype='int')

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [34]:
np.arange(start=10, stop=101, step=9)

array([ 10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [55]:
A = np.linspace(start=2, stop=3, num=24)

In [57]:
A.reshape(3,-1) #automatyczny dobór liczby elementów w wierszu "-1"

array([[2.        , 2.04347826, 2.08695652, 2.13043478, 2.17391304,
        2.2173913 , 2.26086957, 2.30434783],
       [2.34782609, 2.39130435, 2.43478261, 2.47826087, 2.52173913,
        2.56521739, 2.60869565, 2.65217391],
       [2.69565217, 2.73913043, 2.7826087 , 2.82608696, 2.86956522,
        2.91304348, 2.95652174, 3.        ]])

In [59]:
A.reshape(-1,6)

array([[2.        , 2.04347826, 2.08695652, 2.13043478, 2.17391304,
        2.2173913 ],
       [2.26086957, 2.30434783, 2.34782609, 2.39130435, 2.43478261,
        2.47826087],
       [2.52173913, 2.56521739, 2.60869565, 2.65217391, 2.69565217,
        2.73913043],
       [2.7826087 , 2.82608696, 2.86956522, 2.91304348, 2.95652174,
        3.        ]])

In [60]:
np.random.seed(0)

In [61]:
np.random.randn()

1.764052345967664

In [64]:
A = np.random.randn(10,4)
A

array([[ 0.90082649,  0.46566244, -1.53624369,  1.48825219],
       [ 1.89588918,  1.17877957, -0.17992484, -1.07075262],
       [ 1.05445173, -0.40317695,  1.22244507,  0.20827498],
       [ 0.97663904,  0.3563664 ,  0.70657317,  0.01050002],
       [ 1.78587049,  0.12691209,  0.40198936,  1.8831507 ],
       [-1.34775906, -1.270485  ,  0.96939671, -1.17312341],
       [ 1.94362119, -0.41361898, -0.74745481,  1.92294203],
       [ 1.48051479,  1.86755896,  0.90604466, -0.86122569],
       [ 1.91006495, -0.26800337,  0.8024564 ,  0.94725197],
       [-0.15501009,  0.61407937,  0.92220667,  0.37642553]])

In [69]:
x = np.argmax(A)
y = np.unravel_index(np.argmax(A, axis=None), A.shape)
print(x)
print(y)

24
(6, 0)


In [70]:
A[np.unravel_index(np.argmax(A, axis=None), A.shape)]

1.9436211856492926

### Wycinanie

In [71]:
A = np.arange(20)

In [73]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
A[1] # Wycinanie wierszy

array([5, 6, 7, 8, 9])

In [77]:
A[:,1] # Wycinanie kolumn!

array([ 1,  6, 11, 16])

In [79]:
A[1,3]

8

In [86]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [88]:
B=A[1:3]
B=B[:,1:4]
B

array([[ 6,  7,  8],
       [11, 12, 13]])